## Sentiment Analysis

In [47]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/pycaret/pycaret/master/datasets/amazon.csv')
df.head()

                                          reviewText  Positive
0  This is a one of the best apps acording to a b...         1
1  This is a pretty good version of the game for ...         1
2  this is a really cool game. there are a bunch ...         1
3  This is a silly game and can be frustrating, b...         1
4  This is a terrific game on any pad. Hrs of fun...         1

In [48]:
df.tail()

                                              reviewText  Positive
19995  this app is fricken stupid.it froze on the kin...         0
19996  Please add me!!!!! I need neighbors! Ginger101...         1
19997  love it!  this game. is awesome. wish it had m...         1
19998  I love love love this app on my side of fashio...         1
19999  This game is a rip off. Here is a list of thin...         0

In [49]:
df['reviewText'][0]

'This is a one of the best apps acording to a bunch of people and I agree it has bombs eggs pigs TNT king pigs and realustic stuff'

In [50]:
df['reviewText'][1]

'This is a pretty good version of the game for being free. There are LOTS of different levels to play. My kids enjoy it a lot too.'

In [51]:
df['reviewText'][19999]

"This game is a rip off. Here is a list of things TO MAKE IT BETTER&bull; First, you NEED REAL animals&bull; Second, YOU NEED A FARM BARN THING&bull; Next,  You need neigybors and better food.&bull;Then, You need to pick a farmer And a User or stormid's L"

In [52]:
df.shape

(20000, 2)

# VADER

In [53]:
import nltk
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

True

In [54]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
analyzer = SentimentIntensityAnalyzer()
analyzer.polarity_scores('This is good mobile')

{'neg': 0.0, 'neu': 0.508, 'pos': 0.492, 'compound': 0.4404}

In [55]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
analyzer = SentimentIntensityAnalyzer()
analyzer.polarity_scores(df['reviewText'][19999])

{'neg': 0.0, 'neu': 0.932, 'pos': 0.068, 'compound': 0.4404}

In [56]:
df['reviewText'][2496]

'oh my goodness this app suuuuuuuuuuuucksss!!!!! the device does the game for you. do not get- do not get this horrid app!'

In [57]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
analyzer = SentimentIntensityAnalyzer()
analyzer.polarity_scores(df['reviewText'][2496])

{'neg': 0.187, 'neu': 0.707, 'pos': 0.106, 'compound': -0.5095}

In [58]:
def get_sentiment(text):
    score = analyzer.polarity_scores(text)
    return 1 if score['pos'] > score['neg'] else 0

df['SentimentVAD'] = df['reviewText'].apply(get_sentiment)

In [59]:
df.head()

                                          reviewText  Positive  SentimentVAD
0  This is a one of the best apps acording to a b...         1             1
1  This is a pretty good version of the game for ...         1             1
2  this is a really cool game. there are a bunch ...         1             1
3  This is a silly game and can be frustrating, b...         1             1
4  This is a terrific game on any pad. Hrs of fun...         1             1

In [60]:
df['Positive'].value_counts()

Positive
1    15233
0     4767
Name: count, dtype: int64

In [61]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(df['Positive'], df['SentimentVAD'])
print(f'Accuracy of VADER Sentiment Analysis: {accuracy*100:.2f}%')

Accuracy of VADER Sentiment Analysis: 81.76%

In [62]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(df['Positive'], df['SentimentVAD']))

[[ 2776  1991]
 [ 1657 13576]]

In [63]:
from sklearn.metrics import classification_report
print(classification_report(df['Positive'], df['SentimentVAD']))

              precision    recall  f1-score   support

           0       0.63      0.58      0.60      4767
           1       0.87      0.89      0.88     15233

    accuracy                           0.82     20000
   macro avg       0.75      0.74      0.74     20000
weighted avg       0.81      0.82      0.82     20000

# TextBlob

In [64]:
%pip install -q textblob
from textblob import TextBlob
TextBlob("This is a good mobile").sentiment

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

Sentiment(polarity=0.7, subjectivity=0.6000000000000001)

In [65]:
TextBlob('This is a good mobile').sentiment.polarity

0.7

In [66]:
TextBlob("This is terrible").sentiment.polarity

-1.0

In [67]:
TextBlob(df['reviewText'][0]).sentiment

Sentiment(polarity=1.0, subjectivity=0.3)

In [68]:
TextBlob(df['reviewText'][19999]).sentiment

Sentiment(polarity=0.09166666666666667, subjectivity=0.2555555555555556)

In [69]:
TextBlob(df['reviewText'][2496]).sentiment

Sentiment(polarity=-0.5, subjectivity=0.4)

In [70]:
def get_sentiment_tb(text):
    polarity = TextBlob(text).sentiment.polarity
    return 1 if polarity > 0 else 0

df['SentimentTB'] = df['reviewText'].apply(get_sentiment_tb)

In [71]:
df.head()

,reviewText,Positive,SentimentVAD,SentimentTB
0,This is a one of the best apps acording to a b...,1,1,1
1,This is a pretty good version of the game for ...,1,1,1
2,this is a really cool game. there are a bunch ...,1,1,1
3,"This is a silly game and can be frustrating, b...",1,1,0
4,This is a terrific game on any pad. Hrs of fun...,1,1,1

In [72]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(df['Positive'], df['SentimentTB'])
print(f'Accuracy of TextBlob Sentiment Analysis: {accuracy*100:.2f}%')

Accuracy of TextBlob Sentiment Analysis: 80.52%

In [73]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(df['Positive'], df['SentimentTB']))

[[ 2838  1929]
 [ 1968 13265]]

In [74]:
from sklearn.metrics import classification_report
print(classification_report(df['Positive'], df['SentimentTB']))

              precision    recall  f1-score   support

           0       0.59      0.60      0.59      4767
           1       0.87      0.87      0.87     15233

    accuracy                           0.81     20000
   macro avg       0.73      0.73      0.73     20000
weighted avg       0.81      0.81      0.81     20000

# Lab Exercise

Build your own classifire (e.g. Multinominal Naive Bayes) to predict the sentiment of the text

In [76]:
import re
import joblib
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_auc_score, roc_curve

In [ ]:
#Prepare data
df = df[['reviewText', 'Positive']].copy()  # reuse existing df
df['reviewText'] = df['reviewText'].fillna('')
def clean_text(text):
    text = text.lower()
    text = re.sub(r'http\S+', ' ', text)               # remove urls
    text = re.sub(r'[^a-z0-9\s]', ' ', text)           # keep alphanumerics and spaces
    text = re.sub(r'\s+', ' ', text).strip()           # normalize whitespace
    return text
df['clean'] = df['reviewText'].astype(str).apply(clean_text)

In [ ]:
#Split
X = df['clean']
y = df['Positive'].astype(int)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [75]:
y_train.value_counts()

Positive
1    12186
0     3814
Name: count, dtype: int64

In [78]:
vectorizer = CountVectorizer()
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)
model = MultinomialNB()
model.fit(X_train_vec, y_train)

MultinomialNB()

In [39]:
#TF-IDF -> MultinomialNB
pipeline = Pipeline([
    ('tfidf', TfidfVectorizer(ngram_range=(1,2), max_df=0.9, min_df=5, stop_words='english')),
    ('clf', MultinomialNB())
])
pipeline.fit(X_train, y_train)

Pipeline(steps=[('tfidf',
                 TfidfVectorizer(max_df=0.9, min_df=5, ngram_range=(1, 2),
                                 stop_words='english')),
                ('clf', MultinomialNB())])

In [77]:
#Evaluate baseline model
y_pred = pipeline.predict(X_test)
y_proba = pipeline.predict_proba(X_test)[:,1] if hasattr(pipeline, "predict_proba") else None

print("Baseline Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Baseline Accuracy: 0.87275

Classification Report:
               precision    recall  f1-score   support

           0       0.89      0.53      0.66       953
           1       0.87      0.98      0.92      3047

    accuracy                           0.87      4000
   macro avg       0.88      0.75      0.79      4000
weighted avg       0.87      0.87      0.86      4000


Confusion Matrix:
 [[ 505  448]
 [  61 2986]]

In [41]:
# Cross-validation (F1)
cv_scores = cross_val_score(pipeline, X, y, cv=5, scoring='f1', n_jobs=-1)
print(f"\n5-fold CV F1 scores: {cv_scores}\nMean CV F1: {cv_scores.mean():.4f}")

5-fold CV F1 scores: [0.91995698 0.91624714 0.90043424 0.91623357 0.92981085]
Mean CV F1: 0.9165

In [42]:
#Hyperparameter tuning
param_grid = {
    'tfidf__max_df': [0.8, 0.9],
    'tfidf__min_df': [1, 3, 5],
    'tfidf__ngram_range': [(1,1), (1,2)],
    'clf__alpha': [0.1, 0.5, 1.0]
}
grid = GridSearchCV(pipeline, param_grid, cv=3, scoring='f1', n_jobs=-1, verbose=1)
grid.fit(X_train, y_train)
print("Grid best params:", grid.best_params_)
best_model = grid.best_estimator_

Fitting 3 folds for each of 36 candidates, totalling 108 fits
Grid best params: {'clf__alpha': 0.1, 'tfidf__max_df': 0.8, 'tfidf__min_df': 3, 'tfidf__ngram_range': (1, 2)}

In [79]:
# Evaluate 
y_pred_best = best_model.predict(X_test)
y_proba_best = best_model.predict_proba(X_test)[:,1] if hasattr(best_model, "predict_proba") else None
print("\nBest Model Accuracy:", accuracy_score(y_test, y_pred_best))
print("\nBest Model Classification Report:\n", classification_report(y_test, y_pred_best))
print("\nBest Model Confusion Matrix:\n", confusion_matrix(y_test, y_pred_best))

Best Model Accuracy: 0.89075

Best Model Classification Report:
               precision    recall  f1-score   support

           0       0.85      0.66      0.74       953
           1       0.90      0.96      0.93      3047

    accuracy                           0.89      4000
   macro avg       0.87      0.81      0.84      4000
weighted avg       0.89      0.89      0.89      4000


Best Model Confusion Matrix:
 [[ 628  325]
 [ 112 2935]]

In [ ]:
# Inspect 
vect = best_model.named_steps['tfidf']
clf = best_model.named_steps['clf']
feature_names = vect.get_feature_names_out()
topn = 20
for i, class_label in enumerate(clf.classes_):
    top_indices = np.argsort(clf.feature_log_prob_[i])[::-1][:topn]
    top_features = [feature_names[j] for j in top_indices]
    print(f"\nTop {topn} tokens for class {class_label}:\n", top_features)

Top 20 tokens for class 0:
 ['app', 'game', 'don', 'just', 'work', 'time', 'like', 'kindle', 'waste', 'does', 'free', 'download', 'didn', 'doesn', 'did', 'play', 'quot', 'tried', 'stupid', 'really']

Top 20 tokens for class 1:
 ['app', 'game', 'love', 'great', 'use', 'like', 'fun', 'easy', 'kindle', 'just', 'really', 'good', 'play', 'works', 'time', 'free', 'don', 'best', 'recommend', 'easy use']